// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqfqmkrtzalcufrlrjkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxZnFta3J0emFsY3Vmcmxyamt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDI0NDksImV4cCI6MjA2MDk3ODQ0OX0.13_rk0ljbGYgdgRPoNEDS9YZD-a8olHLLac_aQZ5y8M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);